/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class kalkulator_ukk extends javax.swing.JFrame {
String bilangan="";
double jumlah,bilangan1,bilangan2;
int pilih;
    /**
     * Creates new form kalkulator_ukk
     */
    public kalkulator_ukk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bil7 = new javax.swing.JButton();
        bil3 = new javax.swing.JButton();
        bil6 = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        bil1 = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        bil0 = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bil8 = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        bil5 = new javax.swing.JButton();
        bil2 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        bil9 = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        bil4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\calculator-385506_1280.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bil7.setText("7");
        bil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil7ActionPerformed(evt);
            }
        });
        jPanel1.add(bil7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 95, 85));

        bil3.setText("3");
        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        jPanel1.add(bil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 88, 80));

        bil6.setText("6");
        bil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil6ActionPerformed(evt);
            }
        });
        jPanel1.add(bil6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 95, 85));

        samadengan.setBackground(new java.awt.Color(255, 153, 153));
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 88, 85));

        bil1.setText("1");
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        jPanel1.add(bil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 95, 82));

        tambah.setBackground(new java.awt.Color(255, 153, 153));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 84, 85));

        bil0.setText("0");
        bil0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil0ActionPerformed(evt);
            }
        });
        jPanel1.add(bil0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 95, 82));

        kurang.setBackground(new java.awt.Color(255, 153, 153));
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 84, 85));

        hapus.setBackground(new java.awt.Color(255, 0, 51));
        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 95, 87));

        kali.setBackground(new java.awt.Color(255, 153, 153));
        kali.setText("x");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 84, 79));

        bil8.setText("8");
        bil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil8ActionPerformed(evt);
            }
        });
        jPanel1.add(bil8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 89, 85));

        bagi.setBackground(new java.awt.Color(255, 153, 153));
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 84, 82));

        bil5.setText("5");
        bil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil5ActionPerformed(evt);
            }
        });
        jPanel1.add(bil5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 89, 82));

        bil2.setText("2");
        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        jPanel1.add(bil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 89, 82));

        koma.setBackground(new java.awt.Color(255, 153, 153));
        koma.setText(",");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel1.add(koma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 89, 82));

        bil9.setText("9");
        bil9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil9ActionPerformed(evt);
            }
        });
        jPanel1.add(bil9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 88, 85));

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 530, 69));

        bil4.setText("4");
        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        jPanel1.add(bil4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 88, 85));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\calculator-385506_1280.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 670, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
        bilangan +="4";
        hasil.setText (bilangan);
    }//GEN-LAST:event_bil4ActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void bil9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil9ActionPerformed
        bilangan +="9";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil9ActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        bilangan +=".";
        hasil.setText(bilangan);
    }//GEN-LAST:event_komaActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        bilangan +="2";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil5ActionPerformed
        bilangan +="5";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil5ActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        bilangan1 =Double.parseDouble(bilangan);
        hasil.setText("/");
        bilangan="";
        pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void bil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil8ActionPerformed
        bilangan +="8";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil8ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        bilangan1 =Double.parseDouble(bilangan);
        hasil.setText("x");
        bilangan="";
        pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        hasil.setText(null);
        bilangan1=0.0;
        bilangan2=0.0;
        jumlah=0.0;
        bilangan="";
    }//GEN-LAST:event_hapusActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        bilangan1 =Double.parseDouble(bilangan);
        hasil.setText("-");
        bilangan="";
        pilih=2;
    }//GEN-LAST:event_kurangActionPerformed

    private void bil0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil0ActionPerformed
        bilangan +="0";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil0ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        bilangan1 =Double.parseDouble(bilangan);
        hasil.setText("+");
        bilangan="";
        pilih=1;
    }//GEN-LAST:event_tambahActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        bilangan +="1";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil1ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        switch(pilih){
            case 1:
            bilangan2 = Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bilangan1+bilangan2;
            bilangan = Double.toString(jumlah);
            break;
            case 2:
            bilangan2 =Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bilangan1 - bilangan2;
            bilangan = Double.toString(jumlah);
            break;
            case 3:
            bilangan2 = Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bilangan1 * bilangan2;
            bilangan = Double.toString(jumlah);
            break;
            case 4:
            bilangan2 = Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bilangan1 / bilangan2;
            bilangan = Double.toString(jumlah);
            break;
        }
        hasil.setText(bilangan);
    }//GEN-LAST:event_samadenganActionPerformed

    private void bil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil6ActionPerformed
        bilangan +="6";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil6ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        bilangan +="3";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil7ActionPerformed
        bilangan +="7";
        hasil.setText(bilangan);
    }//GEN-LAST:event_bil7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator_ukk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator_ukk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator_ukk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator_ukk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator_ukk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JButton bil0;
    private javax.swing.JButton bil1;
    private javax.swing.JButton bil2;
    private javax.swing.JButton bil3;
    private javax.swing.JButton bil4;
    private javax.swing.JButton bil5;
    private javax.swing.JButton bil6;
    private javax.swing.JButton bil7;
    private javax.swing.JButton bil8;
    private javax.swing.JButton bil9;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
